export const defaultWordBooks = [
    {
        id: 'default-1',
        name: '基础词汇',
        isDefault: true,
        words: [
            { english: 'hello', chinese: '你好' },
            { english: 'world', chinese: '世界' },
            { english: 'computer', chinese: '计算机' },
            { english: 'language', chinese: '语言' },
            { english: 'study', chinese: '学习' },
            { english: 'book', chinese: '书' },
            { english: 'friend', chinese: '朋友' },
            { english: 'time', chinese: '时间' },
            { english: 'life', chinese: '生活' },
            { english: 'work', chinese: '工作' },
            { english: 'school', chinese: '学校' },
            { english: 'teacher', chinese: '老师' },
            { english: 'student', chinese: '学生' },
            { english: 'family', chinese: '家庭' },
            { english: 'food', chinese: '食物' }
        ]
    },
    {
        id: 'default-2',
        name: '常用短语',
        isDefault: true,
        words: [
            { english: 'good morning', chinese: '早上好' },
            { english: 'good night', chinese: '晚安' },
            { english: 'thank you', chinese: '谢谢你' },
            { english: 'you are welcome', chinese: '不客气' },
            { english: 'nice to meet you', chinese: '很高兴见到你' },
            { english: 'how are you', chinese: '你好吗' },
            { english: 'see you later', chinese: '待会见' },
            { english: 'take care', chinese: '保重' },
            { english: 'excuse me', chinese: '对不起，打扰一下' },
            { english: 'I understand', chinese: '我明白了' },
            { english: 'have a good day', chinese: '祝你今天愉快' },
            { english: 'I miss you', chinese: '我想你' },
            { english: 'get well soon', chinese: '早日康复' },
            { english: 'happy birthday', chinese: '生日快乐' },
            { english: 'congratulations', chinese: '恭喜' }
        ]
    },
    {
        "id": "4B_Unit2",
        "name": "4B_Unit2",
        "isDefault": true,
        "words": [
            { "english": "balanced diet", "chinese": "均衡飲食" },
            { "english": "bread and cereals", "chinese": "麵包和穀類食物" },
            { "english": "dairy products", "chinese": "奶類產品" },
            { "english": "food pyramid", "chinese": "食物金字塔" },
            { "english": "fried food", "chinese": "油炸食物" },
            { "english": "fruit and vegetables", "chinese": "水果和蔬菜" },
            { "english": "meat", "chinese": "肉類" },
            { "english": "noodles and pasta", "chinese": "麵" },
            { "english": "seafood", "chinese": "海鮮" },
            { "english": "junk food", "chinese": "垃圾食品" },
            { "english": "explain", "chinese": "解釋" },
            { "english": "food group", "chinese": "食物種類" },
            { "english": "castle", "chinese": "城堡" },
            { "english": "fountain", "chinese": "噴水池" },
            { "english": "dip", "chinese": "蘸/浸" },
            { "english": "delicious", "chinese": "美味的" },
            { "english": "nothing", "chinese": "沒有一件東西" },
            { "english": "worried", "chinese": "擔心的" },
            { "english": "receive", "chinese": "收到" },
            { "english": "advice", "chinese": "忠告/建議" },
            { "english": "invitation", "chinese": "邀請" },
            { "english": "sweets", "chinese": "糖果" },
            { "english": "oil", "chinese": "食用油" },
            { "english": "label", "chinese": "標籤" },
            { "english": "contain", "chinese": "包含/含有" },
            { "english": "per", "chinese": "每每一" },
            { "english": "energy", "chinese": "能量" },
            { "english": "protein", "chinese": "蛋白質" },
            { "english": "fat", "chinese": "脂肪" },
            { "english": "sugar", "chinese": "糖" },
            { "english": "amount", "chinese": "數量" }
        ]
    },
    {
        "id": "4A-U1toU5",
        "name": "4A-U1toU5",
        "isDefault": true,
        "words": [
            { "english": "do a jigsaw puzzle", "chinese": "砌拼圖" },
            { "english": "do karate", "chinese": "打空手道" },
            { "english": "go cycling", "chinese": "踏單車" },
            { "english": "go jogging", "chinese": "慢跑" },
            { "english": "go roller skating", "chinese": "玩滾軸溜冰" },
            { "english": "go skate boarding", "chinese": "玩滑板" },
            { "english": "play the ukulele", "chinese": "彈夏威夷小吉他" },
            { "english": "watch a magic show", "chinese": "看魔術表演" },
            { "english": "watch a concert", "chinese": "聽音樂會" },
            { "english": "play Frisbee", "chinese": "玩飛碟" },
            { "english": "talk to", "chinese": "談話" },
            { "english": "listen to", "chinese": "聆聽" },
            { "english": "look after", "chinese": "照顧" },
            { "english": "play with", "chinese": "與……玩耍" },
            { "english": "make fun of", "chinese": "捉弄(某人)" },
            { "english": "shout at", "chinese": "對……大叫" },
            { "english": "argue with", "chinese": "跟……争吵" },
            { "english": "fight with", "chinese": "跟……打架" },
            { "english": "laugh at", "chinese": "取笑" },
            { "english": "rude", "chinese": "無禮的" },
            { "english": "noise", "chinese": "吵鬧聲" },
            { "english": "say sorry to", "chinese": "道歉" },
            { "english": "calm", "chinese": "冷靜的" },
            { "english": "friendly", "chinese": "友善的" },
            { "english": "healthy", "chinese": "健康的" },
            { "english": "humble", "chinese": "謙卑的" },
            { "english": "naughty", "chinese": "顽皮的" },
            { "english": "neat", "chinese": "整齊的" },
            { "english": "pretty", "chinese": "漂亮的" },
            { "english": "shy", "chinese": "害羞的" },
            { "english": "smart", "chinese": "聰明的" },
            { "english": "sporty", "chinese": "愛好運動的" },
            { "english": "adventure story", "chinese": "冒險故事" },
            { "english": "detective story", "chinese": "偵探故事" },
            { "english": "fairy tale", "chinese": "童話故事" },
            { "english": "horror story", "chinese": "恐怖故事" },
            { "english": "love story", "chinese": "愛情故事" },
            { "english": "true story", "chinese": "真實的故事" },
            { "english": "boring", "chinese": "無趣的" },
            { "english": "exciting", "chinese": "刺激的" },
            { "english": "frightening", "chinese": "可怕的" },
            { "english": "interesting", "chinese": "有趣的" },
            { "english": "popular", "chinese": "受歡迎的" },
            { "english": "touching", "chinese": "感人的" },
            { "english": "Easter", "chinese": "復活節" },
            { "english": "Dragon Boat Festival", "chinese": "端午節" },
            { "english": "Mid-Autumn Festival", "chinese": "中秋節" },
            { "english": "Christmas", "chinese": "聖誕節" },
            { "english": "paint Easter eggs", "chinese": "晝復活節彩蛋" },
            { "english": "Halloween", "chinese": "萬聖節" },
            { "english": "eat rice dumplings", "chinese": "吃糉" },
            { "english": "watch dragon boat races", "chinese": "看龍舟競賽" },
            { "english": "eat mooncakes", "chinese": "吃月餅" },
            { "english": "play with lanterns", "chinese": "玩燈籠" }
        ]
    }
];