export const defaultWordBooks = [
    {
        "id": "4B_Unit2",
        "name": "4B_Unit2",
        "isDefault": true,
        "words": [
            { "english": "balanced diet", "chinese": "均衡飲食" },
            { "english": "bread and cereals", "chinese": "麵包和穀類食物" },
            { "english": "dairy products", "chinese": "奶類產品" },
            { "english": "food pyramid", "chinese": "食物金字塔" },
            { "english": "fried food", "chinese": "油炸食物" },
            { "english": "fruit and vegetables", "chinese": "水果和蔬菜" },
            { "english": "meat", "chinese": "肉類" },
            { "english": "noodles and pasta", "chinese": "麵" },
            { "english": "seafood", "chinese": "海鮮" },
            { "english": "junk food", "chinese": "垃圾食品" },
            { "english": "explain", "chinese": "解釋" },
            { "english": "food group", "chinese": "食物種類" },
            { "english": "castle", "chinese": "城堡" },
            { "english": "fountain", "chinese": "噴水池" },
            { "english": "dip", "chinese": "蘸/浸" },
            { "english": "delicious", "chinese": "美味的" },
            { "english": "nothing", "chinese": "沒有一件東西" },
            { "english": "worried", "chinese": "擔心的" },
            { "english": "receive", "chinese": "收到" },
            { "english": "advice", "chinese": "忠告/建議" },
            { "english": "invitation", "chinese": "邀請" },
            { "english": "sweets", "chinese": "糖果" },
            { "english": "oil", "chinese": "食用油" },
            { "english": "label", "chinese": "標籤" },
            { "english": "contain", "chinese": "包含/含有" },
            { "english": "per", "chinese": "每/每一" },
            { "english": "energy", "chinese": "能量" },
            { "english": "protein", "chinese": "蛋白質" },
            { "english": "fat", "chinese": "脂肪" },
            { "english": "sugar", "chinese": "糖" },
            { "english": "amount", "chinese": "數量" }
        ]
    },
    {
        "id": "4A-U1toU5",
        "name": "4A-U1toU5",
        "isDefault": true,
        "words": [
            { "english": "do a jigsaw puzzle", "chinese": "砌拼圖" },
            { "english": "do karate", "chinese": "打空手道" },
            { "english": "go cycling", "chinese": "踏單車" },
            { "english": "go jogging", "chinese": "慢跑" },
            { "english": "go roller skating", "chinese": "玩滾軸溜冰" },
            { "english": "go skate boarding", "chinese": "玩滑板" },
            { "english": "play the ukulele", "chinese": "彈夏威夷小吉他" },
            { "english": "watch a magic show", "chinese": "看魔術表演" },
            { "english": "watch a concert", "chinese": "聽音樂會" },
            { "english": "play Frisbee", "chinese": "玩飛碟" },
            { "english": "talk to", "chinese": "談話" },
            { "english": "listen to", "chinese": "聆聽" },
            { "english": "look after", "chinese": "照顧" },
            { "english": "play with", "chinese": "與……玩耍" },
            { "english": "make fun of", "chinese": "捉弄(某人)" },
            { "english": "shout at", "chinese": "對……大叫" },
            { "english": "argue with", "chinese": "跟……争吵" },
            { "english": "fight with", "chinese": "跟……打架" },
            { "english": "laugh at", "chinese": "取笑" },
            { "english": "rude", "chinese": "無禮的" },
            { "english": "noise", "chinese": "吵鬧聲" },
            { "english": "say sorry to", "chinese": "道歉" },
            { "english": "calm", "chinese": "冷靜的" },
            { "english": "friendly", "chinese": "友善的" },
            { "english": "healthy", "chinese": "健康的" },
            { "english": "humble", "chinese": "謙卑的" },
            { "english": "naughty", "chinese": "顽皮的" },
            { "english": "neat", "chinese": "整齊的" },
            { "english": "pretty", "chinese": "漂亮的" },
            { "english": "shy", "chinese": "害羞的" },
            { "english": "smart", "chinese": "聰明的" },
            { "english": "sporty", "chinese": "愛好運動的" },
            { "english": "adventure story", "chinese": "冒險故事" },
            { "english": "detective story", "chinese": "偵探故事" },
            { "english": "fairy tale", "chinese": "童話故事" },
            { "english": "horror story", "chinese": "恐怖故事" },
            { "english": "love story", "chinese": "愛情故事" },
            { "english": "true story", "chinese": "真實的故事" },
            { "english": "boring", "chinese": "無趣的" },
            { "english": "exciting", "chinese": "刺激的" },
            { "english": "frightening", "chinese": "可怕的" },
            { "english": "interesting", "chinese": "有趣的" },
            { "english": "popular", "chinese": "受歡迎的" },
            { "english": "touching", "chinese": "感人的" },
            { "english": "Easter", "chinese": "復活節" },
            { "english": "Dragon Boat Festival", "chinese": "端午節" },
            { "english": "Mid-Autumn Festival", "chinese": "中秋節" },
            { "english": "Christmas", "chinese": "聖誕節" },
            { "english": "paint Easter eggs", "chinese": "畫復活節彩蛋" },
            { "english": "Halloween", "chinese": "萬聖節" },
            { "english": "eat rice dumplings", "chinese": "吃糉" },
            { "english": "watch dragon boat races", "chinese": "看龍舟競賽" },
            { "english": "eat mooncakes", "chinese": "吃月餅" },
            { "english": "play with lanterns", "chinese": "玩燈籠" }
        ]
    },
    {
        "id": "4B_Unit1",
        "name": "4B Unit1 - The story of Princess Milky (Part 1)",
        "isDefault": true,
        "words": [
            { "english": "a bar of chocolate", "chinese": "一塊巧克力" },
            { "english": "a jar of nuts", "chinese": "一瓶堅果" },
            { "english": "a loaf of garlic bread", "chinese": "一條蒜蓉包" },
            { "english": "a packet of sausages", "chinese": "一包香腸" },
            { "english": "chicken nuggets", "chinese": "雞塊" },
            { "english": "cupcakes", "chinese": "紙杯蛋糕" },
            { "english": "fish balls", "chinese": "魚蛋" },
            { "english": "a ham and mushroom pizza", "chinese": "一個火腿蘑菇薄餅" },
            { "english": "mango pudding", "chinese": "芒果布丁" },
            { "english": "onion rings", "chinese": "洋葱圈" },
            { "english": "snacks", "chinese": "小吃" },
            { "english": "fairy tale", "chinese": "童話（故事）" },
            { "english": "polite", "chinese": "有禮貌的" },
            { "english": "cook", "chinese": "廚師" },
            { "english": "guest", "chinese": "客人" },
            { "english": "idiom", "chinese": "成語/慣用語" },
            { "english": "spell", "chinese": "咒語/魔法" },
            { "english": "healthy", "chinese": "健康的" },
            { "english": "disappointed", "chinese": "失望的" },
            { "english": "thankful", "chinese": "感激的" },
            { "english": "excited", "chinese": "興奮的" },
            { "english": "at once", "chinese": "馬上/立刻" },
            { "english": "plenty of", "chinese": "大量的/充足的" },
            { "english": "a few", "chinese": "有些/幾個" },
            { "english": "a little", "chinese": "少量的/一些" },
            { "english": "fork", "chinese": "餐叉" }
        ]
    },
    {
        "id": "4B_Unit3",
        "name": "4B Unit3 - Museum Day",
        "isDefault": true,
        "words": [
            { "english": "entrance", "chinese": "入口" },
            { "english": "exit", "chinese": "出口" },
            { "english": "escalator", "chinese": "自動扶梯" },
            { "english": "lift", "chinese": "電梯/升降機" },
            { "english": "display", "chinese": "展品" },
            { "english": "exhibition hall", "chinese": "展覽廳" },
            { "english": "information board", "chinese": "資訊板" },
            { "english": "theatre", "chinese": "劇場" },
            { "english": "souvenir shop", "chinese": "紀念品商店" },
            { "english": "ticket counter", "chinese": "售票處" },
            { "english": "museum", "chinese": "博物館" },
            { "english": "directory", "chinese": "指南" },
            { "english": "zone", "chinese": "區/區域" },
            { "english": "dinosaur", "chinese": "恐龍" },
            { "english": "sound", "chinese": "聽起來好像" },
            { "english": "behave", "chinese": "表现得體" },
            { "english": "fright", "chinese": "驚嚇" },
            { "english": "safety belt", "chinese": "安全帶" },
            { "english": "stairs", "chinese": "樓梯" }
        ]
    },
    {
        "id": "4B_Unit4",
        "name": "4B Unit4 - A fun time",
        "isDefault": true,
        "words": [
            { "english": "buy snacks at a food stall", "chinese": "在食品攤檔買小吃" },
            { "english": "do face painting", "chinese": "玩臉部彩繪" },
            { "english": "take photos with the clowns", "chinese": "跟小丑拍照" },
            { "english": "twist balloons", "chinese": "扭氣球" },
            { "english": "bumper car", "chinese": "碰碰車" },
            { "english": "game booth", "chinese": "遊戲攤位" },
            { "english": "jumping castle", "chinese": "充氣城堡" },
            { "english": "merry-go-round", "chinese": "旋轉木馬" },
            { "english": "roller coaster", "chinese": "過山車" },
            { "english": "Ferris wheel", "chinese": "摩天輪" },
            { "english": "funfair", "chinese": "嘉年華" },
            { "english": "proudly", "chinese": "自豪地" },
            { "english": "present", "chinese": "展现/介绍" },
            { "english": "spread", "chinese": "傳播/(使)流傳" },
            { "english": "amazing", "chinese": "令人驚歎的" },
            { "english": "humorous", "chinese": "滑稽有趣的" },
            { "english": "adult", "chinese": "成年人" },
            { "english": "free", "chinese": "免費的" },
            { "english": "admission", "chinese": "入場費" },
            { "english": "slightly", "chinese": "稍微" },
            { "english": "last", "chinese": "持續" },
            { "english": "permission", "chinese": "准許/許可" },
            { "english": "lollipop", "chinese": "棒棒糖" },
            { "english": "popcorn", "chinese": "爆米花" },
            { "english": "event", "chinese": "公開活動" }
        ]
    },
    {
        "id": "4B_Unit5",
        "name": "4B Unit5 - Out with the Cubs",
        "isDefault": true,
        "words": [
            { "english": "carefully", "chinese": "小心地" },
            { "english": "carelessly", "chinese": "粗grounds" },
            { "english": "happily", "chinese": "高興地" },
            { "english": "sadly", "chinese": "悲傷地" },
            { "english": "loudly", "chinese": "大聲地" },
            { "english": "quietly", "chinese": "安靜地" },
            { "english": "politely", "chinese": "有禮貌地" },
            { "english": "rudely", "chinese": "粗魯地" },
            { "english": "quickly", "chinese": "快速地" },
            { "english": "slowly", "chinese": "慢慢地" },
            { "english": "Cubs", "chinese": "幼童軍" },
            { "english": "campsite", "chinese": "露營營地" },
            { "english": "mission", "chinese": "任務" },
            { "english": "instruction", "chinese": "指示" },
            { "english": "treasure hunt", "chinese": "尋寶遊戲" },
            { "english": "riddle", "chinese": "談話" },
            { "english": "step", "chinese": "步驟" },
            { "english": "possible", "chinese": "可能的" },
            { "english": "solve", "chinese": "解答/破解" },
            { "english": "location", "chinese": "地點/位置" },
            { "english": "finally", "chinese": "最後" },
            { "english": "split up", "chinese": "劃分" },
            { "english": "search", "chinese": "搜尋" },
            { "english": "dig", "chinese": "掘/挖" },
            { "english": "map", "chinese": "地圖" },
            { "english": "collect", "chinese": "收集" }
        ]
    },
    {
        "id": "4B_Unit6",
        "name": "4B Unit6 - The great escape",
        "isDefault": true,
        "words": [
            { "english": "camel", "chinese": "駱駝" },
            { "english": "giraffe", "chinese": "長頸鹿" },
            { "english": "hippo", "chinese": "河馬" },
            { "english": "snake", "chinese": "蛇" },
            { "english": "zebra", "chinese": "斑馬" },
            { "english": "cave", "chinese": "洞穴" },
            { "english": "desert", "chinese": "沙漠" },
            { "english": "lake", "chinese": "湖" },
            { "english": "mountain", "chinese": "山" },
            { "english": "waterfall", "chinese": "瀑布" },
            { "english": "escape", "chinese": "逃走" },
            { "english": "hometown", "chinese": "家鄉" },
            { "english": "wonderful", "chinese": "使人愉快的" },
            { "english": "sight", "chinese": "視野" },
            { "english": "metre", "chinese": "米/公尺" },
            { "english": "kilogram", "chinese": "千克/公斤" },
            { "english": "centimetre", "chinese": "厘米/公分" },
            { "english": "pond", "chinese": "池塘" },
            { "english": "stomach", "chinese": "胃/腹部" },
            { "english": "complain", "chinese": "抱怨/投訴" },
            { "english": "gate", "chinese": "閘門" },
            { "english": "drop", "chinese": "掉下" },
            { "english": "reach", "chinese": "伸手取" },
            { "english": "fail", "chinese": "失败/未能(做到)" },
            { "english": "never mind", "chinese": "没關係" },
            { "english": "height", "chinese": "身高/高度" },
            { "english": "weight", "chinese": "體重/重量" },
            { "english": "midnight", "chinese": "午夜" }
        ]
    }
];